server:
  port: 8100
  address: localhost
  servlet:
    context-path: /
    session:
      timeout: 1800
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: utf-8

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.pjb.springbootjwt.**.domain
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
debug: true

spring:
  thymeleaf:
    mode: HTML5
    cache: false
  resources:
    static-locations:
      - classpath:/templates
      - classpath:/static
  profiles:
    active: home
  servlet:
    #上传文件设置
    multipart:
      max-file-size: 10MB
      max-request-size:  120MB

#阿里云上传
alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKey: LTAIORfW2jDDGDxz
    accessSecret: tNISEmkZNw0lMzvZ7u09MKkWU5FCDL
    bucketName: hx-dfz
    rootPath: uploads
    viewUrl: http://hx-dfz.oss-cn-shanghai.aliyuncs.com/

#本地上传
upload:
  config:
    #本地存储路径
    store-path: D:\\temp\\
    #访问url(需要通过nginx来访问)
    #server {
    #  listen 8101;
    #  server_name  localhost;
    #  location / {
    #    root D:\\temp;
    #    autoindex on;
    #  }
    #}
    view-url: http://localhost:8101/

#websocket聊天服务器配置
websocket:
  config:
    address: ${server.address}
    port: ${server.port}