#
# 腾讯云环境
#
server:
  address: 121.4.51.186
  port: 8100
  tomcat:
    basedir: ${temp.tomcat.path.linux}

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://58.220.130.183:3306/zhdd?useSSL=false
    username: root
    password: ^klzvG064A7%ERQj
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: 192.168.31.153
    port: 6379
    password: 123456
    database: 0
    timeout: 1000s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: -1

#本地上传
upload:
  config:
    #本地存储路径
    store-path: /home/springbootJwt
    #访问url(需要通过nginx来访问)
    #server {
    #  listen 8101;
    #  server_name  localhost;
    #  location / {
    #    root /home/springbootJwt;
    #    autoindex on;
    #  }
    #}
    view-url: http://121.4.51.186:8101/

#websocket聊天服务器配置
websocket:
  config:
    #如果是内网 就配置成内网IP或者127.0.0.1;如果是外网，配置成公网IP
    address: 121.4.51.186
    port: ${server.port}