server:
  servlet:
    context-path: /
    session:
      timeout: PT2M
  tomcat:
    max-threads: 1000
    min-spare-threads: 30
    uri-encoding: utf-8

mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:/mapper/**/*Mapper.xml

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  typeAliasesPackage: com.pjb.springbootjwt.**.domain
  global-config:
    id-type: 0
    field-strategy: 2
    db-column-underline: true
    capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: true

spring:
  thymeleaf:
    mode: HTML5
    cache: false
  resources:
    static-locations:
      - classpath:/templates
      - classpath:/static
      - classpath:/static/css
  profiles:
    active: home
  servlet:
    #上传文件设置
    multipart:
      max-file-size: 10MB
      max-request-size:  120MB
  messages:
    encoding: UTF-8
    basename: static/i18n/messages
  devtools:
    restart:
      enabled: false
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 547495788@qq.com #发送邮件的邮箱地址
    password: lzfmqwhalxpdbccc  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 547495788@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8


#阿里云上传
alioss:
    endpoint: oss-cn-shanghai.aliyuncs.com
    accessKey: LTAIORfW2jDDGDxz
    accessSecret: tNISEmkZNw0lMzvZ7u09MKkWU5FCDL
    bucketName: hx-dfz
    rootPath: uploads
    viewUrl: http://hx-dfz.oss-cn-shanghai.aliyuncs.com/

#七牛云上传
qiniu:
  accessKey: faaQMfxkZ6FQlosBjIU7fC3AcQzr5YBXrEPZaG1t
  secretKey: zpauQmqiWwxe9IcEkmT6iZxJ4w5NFZ9iGEWkrYNF
  bucket: kimzihun
  domainPath: r56o6jo3n.hd-bkt.clouddn.com

#自定义 tomcat缓存临时目录
temp:
  tomcat:
    path:
      windows: C:\\tomcatTemp
      linux: /opt/tomcatTemp