spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhdd?useSSL=false
    username: root
    password: 123456
  cache:
    ehcache:
      config: classpath:ehcache.xml
  redis:
    host: 192.168.1.42
    port: 6379
    password: 123456
    database: 0
    timeout: 1000s
    jedis:
      pool:
        max-idle: 500
        min-idle: 50
        max-active: -1